# Krok 1: Budowanie aplikacji Angular
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
# Dodajemy flagę --prerender false, aby uniknąć błędu NG0401
RUN npm run build -- --configuration production --prerender false

# Krok 2: Serwowanie aplikacji za pomocą serwera Nginx
FROM nginx:stable-alpine
# UWAGA: Sprawdź dokładnie ścieżkę w folderze dist po nieudanym buildzie
# Zazwyczaj jest to /app/dist/frontend/browser
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]