# Etap 1: Budowanie i Testowanie
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Testy w trybie "headless" bez szukania Windowsowych ścieżek
RUN npx ng test --watch=false --browsers=chrome --no-sandbox

# Budowanie wersji produkcyjnej
RUN npm run build -- --configuration production

# Etap 2: Serwowanie
FROM nginx:stable-alpine
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]